### ISSUE TITLE
markdown行号显示有问题，望修复

### ISSUE THREAD

**Issue by kira-96** [viko16/vuepress-theme-simple#4]
![image](https://user-images.githubusercontent.com/22876709/57984260-ae500280-7a8c-11e9-99a6-eaca04c76421.png)

**Comment by viko16** [comment]
@KKKKKKi 在 `0.7.0` 里修复了，感谢反馈 😄 

![image](https://user-images.githubusercontent.com/5064777/57995583-7af58e00-7af5-11e9-94c0-fd287163ba47.png)

**Comment by kira-96** [comment]
nice! :smiley:
